import type { Metadata } from "next";
import { Inter, 
  // Noto_Kufi_Arabic
 } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });
// const kufiarabic = Noto_Kufi_Arabic({subsets:['arabic'],weight:['300']})
export const metadata: Metadata = {
  title: "Next 14 Arabic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header />
        {children}</body>
    </html>
  );
}
